### ISSUE TITLE
circular import in the RepDL package

### ISSUE THREAD

**Issue by algs7** [microsoft/RepDL#2]
After `pip install .` the repDL package installs correctly, but at runtime there is an import issue:

Can't run the included example:
`RepDL/examples/mnist_trainig.py`

Errors out:
```
ubuntu@fe9006e47214:~/Dev/RepDL/examples$ python3 mnist_trainig.py 
Traceback (most recent call last):
  File "/home/ubuntu/Dev/RepDL/examples/mnist_trainig.py", line 7, in <module>
    import repdl
  File "/home/ubuntu/.local/lib/python3.10/site-packages/repdl/__init__.py", line 8, in <module>
    from . import functional
ImportError: cannot import name 'functional' from partially initialized module 'repdl' (most likely due to a circular import) (/home/ubuntu/.local/lib/python3.10/site-packages/repdl/__init__.py)
```

The same env setup works fine for pure torch training scripts.

**Comment by algs7** [comment]
After fixing the paths and other things in this package, it works!
PR #3 

```
ubuntu@fe9006e47214:~/Dev/RepDL/examples$ python3 reproducible_ops.py 
PyTorch
False
False
False
RepDL
True
True
True
ubuntu@fe9006e47214:~/Dev/RepDL/examples$ python3 mnist_training.py 
Hash of the initial model: 2a2d133895b1684e55d0f152ead2914b55adc551d9790a4b4585309b79c60362
    Epoch [1/2], Iteration [100/600], Loss: 0.2416
    Epoch [1/2], Iteration [200/600], Loss: 0.0867
    Epoch [1/2], Iteration [300/600], Loss: 0.1154
    Epoch [1/2], Iteration [400/600], Loss: 0.1170
    Epoch [1/2], Iteration [500/600], Loss: 0.0344
    Epoch [1/2], Iteration [600/600], Loss: 0.1010
    Epoch [2/2], Iteration [100/600], Loss: 0.0392
    Epoch [2/2], Iteration [200/600], Loss: 0.0281
    Epoch [2/2], Iteration [300/600], Loss: 0.0165
    Epoch [2/2], Iteration [400/600], Loss: 0.0829
    Epoch [2/2], Iteration [500/600], Loss: 0.0383
    Epoch [2/2], Iteration [600/600], Loss: 0.0820
Hash of the trained model: 31ee86a7f75dbd76bac22f209617eb7349f93b0ede116dba924f328cac3013f1
Test accuracy of the model on the 10000 test images: 0.9804
Hash of the logits: 0ca34dcd37105b4af690c46a62407b4b9b097d1063864c6d99f4309aeb4bca3e
```

**Comment by peichenxie** [comment]
Oh, `functional` should be `func`. #3 fixed the issue.
